### ISSUE TITLE
building failed

### ISSUE THREAD

**Issue by moh1122** [tomgiraudet/Notes#1]
hello
Thanks for this great rep
but while building its giving an error in the func save()
its saying :  'managedObjectContext' cannot be used on type 'AppDelegate'

any clue ?

**Comment by tomgiraudet** [comment]
Hi !
Thanks for using this repo.

I developed this app using Swift1. That's why when you tried the building it gave you and error because now xCode uses Swift2.

Now everything should be ok.

If you have other questions, do not hesitate.
Tom.

**Comment by moh1122** [comment]
thanks tom :+1:
